### ISSUE TITLE
RuntimeError: working outside of application context

### ISSUE THREAD

**Issue by adamatan** [doobeh/Flask-S3-Uploader#5]
Hi,

I would like to report an issue I'm having with the uploader. In case that the solution will be of interest to others, I will be more than happy to update the documentation.

# The problem

    $ python app.py
    Traceback (most recent call last):
     File "app.py", line 4, in <module>
       from tools import s3_upload
     File "/private/tmp/Flask-S3-Uploader/tools.py", line 8, in <module>
       def s3_upload(source_file, upload_dir=app.config["S3_UPLOAD_DIRECTORY"], acl='public-read'):
     File "/private/tmp/Flask-S3-Uploader/flask-env/lib/python2.7/site-packages/werkzeug/local.py", line 342, in __getattr__
       return getattr(self._get_current_object(), name)
     File "/private/tmp/Flask-S3-Uploader/flask-env/lib/python2.7/site-packages/werkzeug/local.py", line 301, in _get_current_object
       return self.__local()
     File "/private/tmp/Flask-S3-Uploader/flask-env/lib/python2.7/site-packages/flask/globals.py", line 34, in _find_app
       raise RuntimeError('working outside of application context')
    RuntimeError: working outside of application context

# Steps to reproduce

    $ git clone git@github.com:doobeh/Flask-S3-Uploader.git
    $ cd Flask-S3-Uploader
    $ virtualenv test_env
    $ source test_env/bin/activate
    $ pip install -r requirements.txt

    $ pip freeze
    Flask==0.10.1
    Flask-WTF==0.12
    Jinja2==2.8
    MarkupSafe==0.23
    WTForms==2.0.2
    Werkzeug==0.11.2
    boto==2.38.0
    itsdangerous==0.24
    wsgiref==0.1.2

    $ python app.py
    Traceback (most recent call last):
     File "app.py", line 4, in <module>
       from tools import s3_upload
     File "/private/tmp/Flask-S3-Uploader/tools.py", line 8, in <module>
       def s3_upload(source_file, upload_dir=app.config["S3_UPLOAD_DIRECTORY"], acl='public-read'):
     File "/private/tmp/Flask-S3-Uploader/test_env/lib/python2.7/site-packages/werkzeug/local.py", line 342, in __getattr__
       return getattr(self._get_current_object(), name)
     File "/private/tmp/Flask-S3-Uploader/test_env/lib/python2.7/site-packages/werkzeug/local.py", line 301, in _get_current_object
       return self.__local()
     File "/private/tmp/Flask-S3-Uploader/test_env/lib/python2.7/site-packages/flask/globals.py", line 34, in _find_app
       raise RuntimeError('working outside of application context')
    RuntimeError: working outside of application context
    
# Notes
I have not updates the config file yet, but it does not seem to be related - the error happens before the config file is read. Moreover, even if the details are wrong, the error should only be raised when a file is uploaded to S3 - the `app.py` file should start normally.

**Comment by doobeh** [comment]
Hmm!  Thanks for the nice example-- for a quick fix, you can try and change the `s3_upload` to:

```python
def s3_upload(source_file, upload_dir=None, acl='public-read'):
    """ Uploads WTForm File Object to Amazon S3

        Expects following app.config attributes to be set:
            S3_KEY              :   S3 API Key
            S3_SECRET           :   S3 Secret Key
            S3_BUCKET           :   What bucket to upload to
            S3_UPLOAD_DIRECTORY :   Which S3 Directory.

        The default sets the access rights on the uploaded file to
        public-read.  It also generates a unique filename via
        the uuid4 function combined with the file extension from
        the source file.
    """
    if upload_dir is None:
        upload_dir = app.config["S3_UPLOAD_DIRECTORY"]
        
    source_filename = secure_filename(source_file.data.filename)
    source_extension = os.path.splitext(source_filename)[1]

    destination_filename = uuid4().hex + source_extension

    # Connect to S3 and upload file.
    conn = boto.connect_s3(app.config["S3_KEY"], app.config["S3_SECRET"])
    b = conn.get_bucket(app.config["S3_BUCKET"])

    sml = b.new_key("/".join([upload_dir, destination_filename]))
    sml.set_contents_from_string(source_file.data.read())
    sml.set_acl(acl)

    return destination_filename

```

I wonder why I didn't run into this before, I'll have a further look into it tonight/tomorrow and see what can be fixed.  Thanks again for posting the issue!

**Comment by mikesplain** [comment]
Just for anyone in the future who comes across this, the above fix seemed to work for me.  Thanks @doobeh.

**Comment by doobeh** [comment]
Thanks for commenting on this @mikesplain, finally got me around to committing it to the code

**Comment by adamatan** [comment]
Thanks!
